// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptikSW.Infrastructure.DataAccess;

#nullable disable

namespace OptikSW.Infrastructure.Migrations
{
    [DbContext(typeof(OptikSWDbContext))]
    partial class OptikSWDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OptikSW.Domain.Modules.Customers.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("OptikSW.Domain.Modules.General.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("OptikSW.Domain.Modules.Ordes.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DistanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NearbyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrderAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("Prefix")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistanceId")
                        .IsUnique()
                        .HasFilter("[DistanceId] IS NOT NULL");

                    b.HasIndex("NearbyId")
                        .IsUnique()
                        .HasFilter("[NearbyId] IS NOT NULL");

                    b.HasIndex("OrderAddressId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("OptikSW.Domain.Modules.Ordes.Entities.OrderEyeMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("Frames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FramesPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Layer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LayerPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderEyeMeasurement");

                    b.HasDiscriminator<string>("Discriminator").HasValue("OrderEyeMeasurement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OptikSW.Domain.Modules.Ordes.Entities.OrderEyeMeasurementDistance", b =>
                {
                    b.HasBaseType("OptikSW.Domain.Modules.Ordes.Entities.OrderEyeMeasurement");

                    b.HasDiscriminator().HasValue("OrderEyeMeasurementDistance");
                });

            modelBuilder.Entity("OptikSW.Domain.Modules.Ordes.Entities.OrderEyeMeasurementNearby", b =>
                {
                    b.HasBaseType("OptikSW.Domain.Modules.Ordes.Entities.OrderEyeMeasurement");

                    b.HasDiscriminator().HasValue("OrderEyeMeasurementNearby");
                });

            modelBuilder.Entity("OptikSW.Domain.Modules.Customers.Entities.Customer", b =>
                {
                    b.HasOne("OptikSW.Domain.Modules.General.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("OptikSW.Domain.Modules.Ordes.Entities.Order", b =>
                {
                    b.HasOne("OptikSW.Domain.Modules.Customers.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("OptikSW.Domain.Modules.Ordes.Entities.OrderEyeMeasurementDistance", "Distance")
                        .WithOne("Order")
                        .HasForeignKey("OptikSW.Domain.Modules.Ordes.Entities.Order", "DistanceId");

                    b.HasOne("OptikSW.Domain.Modules.Ordes.Entities.OrderEyeMeasurementNearby", "Nearby")
                        .WithOne("Order")
                        .HasForeignKey("OptikSW.Domain.Modules.Ordes.Entities.Order", "NearbyId");

                    b.HasOne("OptikSW.Domain.Modules.General.Entities.Address", "OrderAddress")
                        .WithMany()
                        .HasForeignKey("OrderAddressId");

                    b.Navigation("Customer");

                    b.Navigation("Distance");

                    b.Navigation("Nearby");

                    b.Navigation("OrderAddress");
                });

            modelBuilder.Entity("OptikSW.Domain.Modules.Ordes.Entities.OrderEyeMeasurement", b =>
                {
                    b.OwnsOne("OptikSW.Domain.Modules.Ordes.Entities.EyeMeasurement", "LeftEye", b1 =>
                        {
                            b1.Property<Guid>("OrderEyeMeasurementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Angle")
                                .HasColumnType("int");

                            b1.Property<string>("Basis")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal?>("Cylinder")
                                .HasPrecision(4, 2)
                                .HasColumnType("decimal(4,2)");

                            b1.Property<int?>("Prisma")
                                .HasColumnType("int");

                            b1.Property<int?>("PupilDistance")
                                .HasColumnType("int");

                            b1.Property<decimal>("Sphere")
                                .HasPrecision(4, 2)
                                .HasColumnType("decimal(4,2)");

                            b1.HasKey("OrderEyeMeasurementId");

                            b1.ToTable("OrderEyeMeasurement");

                            b1.WithOwner()
                                .HasForeignKey("OrderEyeMeasurementId");
                        });

                    b.OwnsOne("OptikSW.Domain.Modules.Ordes.Entities.EyeMeasurement", "RightEye", b1 =>
                        {
                            b1.Property<Guid>("OrderEyeMeasurementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Angle")
                                .HasColumnType("int");

                            b1.Property<string>("Basis")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal?>("Cylinder")
                                .HasPrecision(4, 2)
                                .HasColumnType("decimal(4,2)");

                            b1.Property<int?>("Prisma")
                                .HasColumnType("int");

                            b1.Property<int?>("PupilDistance")
                                .HasColumnType("int");

                            b1.Property<decimal>("Sphere")
                                .HasPrecision(4, 2)
                                .HasColumnType("decimal(4,2)");

                            b1.HasKey("OrderEyeMeasurementId");

                            b1.ToTable("OrderEyeMeasurement");

                            b1.WithOwner()
                                .HasForeignKey("OrderEyeMeasurementId");
                        });

                    b.Navigation("LeftEye")
                        .IsRequired();

                    b.Navigation("RightEye")
                        .IsRequired();
                });

            modelBuilder.Entity("OptikSW.Domain.Modules.Ordes.Entities.OrderEyeMeasurementDistance", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("OptikSW.Domain.Modules.Ordes.Entities.OrderEyeMeasurementNearby", b =>
                {
                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
